name: OAP MLlib CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up dependencies
        run: |
          cd ${{runner.temp}} 
          wget http://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
          tar -zxf spark-3.0.0-bin-hadoop2.7.tgz
          export SPARK_HOME=${{runner.temp}}/spark-3.0.0-bin-hadoop2.7
          ${{github.workspace}}/dev/install-build-deps-ubuntu.sh
      - name: Build and Test
        run: |
          cd ${{github.workspace}}/mllib-dal      
          export ONEAPI_ROOT=/opt/intel/oneapi
          source /opt/intel/oneapi/dal/latest/env/vars.sh
          source /opt/intel/oneapi/tbb/latest/env/vars.sh
          source /tmp/oneCCL/build/_install/env/setvars.sh
          ./test.sh
